AWSTemplateFormatVersion: "2010-09-09"
Description: CFT for the primary EC2 Instance
Parameters:
  TagOrg:
    Type: String
  TagTeam:
    Type: String
  TagApp:
    Type: String
  TagEnv:
    Type: String
  AwsVpcId:
    Type: String
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${TagOrg}-${TagTeam}-${TagApp}-${TagEnv}-EC2-SecurityGroup'
      GroupDescription: The Primary Security Group. Open Traffic
      VpcId: !Ref AwsVpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Organization
          Value: !Ref TagOrg
        - Key: Team
          Value: !Ref TagTeam
        - Key: Application
          Value: !Ref TagApp
        - Key: Purpose
          Value: Primary IAM Role
        - Key: Environment
          Value: !Ref TagEnv
Outputs:
  SecurityGroupId:
    Value: !GetAtt SecurityGroup.GroupId

