AWSTemplateFormatVersion: "2010-09-09"
Description: >
  In this template, we are creating the S3 stack. The stack involves
  creating the S3 bucket itself, the KMS key for data encryption, and the
  bucket policy for access and usage.

Parameters:
  MainIamRoleArn:
    Type: String
    Description: The IAM Role ARN value to use as a principal for both the KMS key policy and bucket policy.

  TagOrg:
    Type: String
    Description: A Key-Value pair stating the organization responsible
  TagTeam:
    Type: String
    Description: A Key-Value pair stating the team responsible
  TagApp:
    Type: String
    Description: A Key-Value pair stating the name of the application
  TagEnv:
    Type: String
    Description: A Key-Value pair stating the environment for the resources created in this cft

  FullBucketNameLowerCase:
    Type: String
    Description: The entire name of the S3 bucket. This is required due to S3 buckets requirement of lowercase name, and this will not support lambda functions.

Resources:

  MainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FullBucketNameLowerCase
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !GetAtt MainBucketKey.Arn
              SSEAlgorithm: aws:kms

      Tags:
        - Key: Organization
          Value: !Ref TagOrg
        - Key: Team
          Value: !Ref TagTeam
        - Key: Application
          Value: !Ref TagApp
        - Key: Purpose
          Value: 'Primary S3 bucket for solitude project'
        - Key: Environment
          Value: !Ref TagEnv

  MainBucketKey:
    Type: AWS::KMS::Key
    Properties:
      Description: A Key to encrypt the files inside the s3 bucket
      EnableKeyRotation: true
      # Normally it's set to 20+ days, but for sake of project 7 is used
      PendingWindowInDays: 7

      KeyPolicy:
        Id: s3-main-key
        Statement:

        - Sid: Allow administration of the key
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action:
            - 'kms:Create*'
            - 'kms:Describe*'
            - 'kms:Enable*'
            - 'kms:List*'
            - 'kms:Put*'
            - 'kms:Update*'
            - 'kms:Revoke*'
            - 'kms:Disable*'
            - 'kms:Get*'
            - 'kms:Delete*'
            - 'kms:ScheduleKeyDeletion'
            - 'kms:CancelKeyDeletion'
          Resource: '*'

        - Sid: Allow the key to be used
          Effect: Allow
          Principal:
            AWS: !Ref MainIamRoleArn
          Action:
            - 'kms:Encrypt'
            - 'kms:Decrypt'
            - 'kms:GenerateDataKey'
          Resource: '*'

      Tags:
        - Key: Organization
          Value: !Ref TagOrg
        - Key: Team
          Value: !Ref TagTeam
        - Key: Application
          Value: !Ref TagApp
        - Key: Purpose
          Value: 'KMS key for bucket encryption'
        - Key: Environment
          Value: !Ref TagEnv

  MainBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FullBucketNameLowerCase
      PolicyDocument:
        Version: 2012-10-17
        Statement:

          - Sid: Allow the IAM Role to use this bucket
            Effect: Allow
            Principal:
              AWS: !Ref MainIamRoleArn
            Action:
            - 's3:ListBucket'
            Resource:
            - !GetAtt MainBucket.Arn

          - Sid: Allow the IAM Role to upload to and download from the bucket
            Effect: Allow
            Principal:
              AWS: !Ref MainIamRoleArn
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource:
              - !Sub '${MainBucket.Arn}/*'

Outputs:
  MainBucketArn:
    Value: !GetAtt MainBucket.Arn
    Description: The Main Bucket ARN for policies that require it.
  MainBucketKeyArn:
    Value: !GetAtt MainBucketKey.Arn
    Description: The Main Bucket KMS Key ARN for policies that require it.

