AWSTemplateFormatVersion: "2010-09-09"
Description: CFT For the primary IAM Role
Parameters:
  TagOrg:
    Type: String
  TagTeam:
    Type: String
  TagApp:
    Type: String
  TagEnv:
    Type: String
Resources:
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${TagOrg}-${TagTeam}-${TagApp}-${TagEnv}-IAM-Role'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Tags:
        - Key: Organization
          Value: !Ref TagOrg
        - Key: Team
          Value: !Ref TagTeam
        - Key: Application
          Value: !Ref TagApp
        - Key: Purpose
          Value: Primary IAM Role
        - Key: Environment
          Value: !Ref TagEnv
Outputs:
  IamRoleArn:
    Value: !GetAtt IamRole.Arn

