AWSTemplateFormatVersion: "2010-09-09"
Description: >
  In this template, we are creating the EC2 stack. The stack involves
  creating the EC2's security group to have open traffic, The IAM Profile
  for the session manager, and finally the EC2 instance to have a linux
  instance.
Parameters:
  MainVpcId:
    Type: String
    Description: The VPC ID from the shared VPC resource
  MainVpcSubnetId:
    Type: String
    Description: The VPC subnet ID from the shared subnet resource
  MainSshKeyPairName:
    Type: String
    Description: The SSH key-pair name from the shared keypair resource
  TagOrg:
    Type: String
    Description: A Key-Value pair stating the organization responsible
  TagTeam:
    Type: String
    Description: A Key-Value pair stating the team responsible
  TagApp:
    Type: String
    Description: A Key-Value pair stating the name of the application
  TagEnv:
    Type: String
    Description: A Key-Value pair stating the environment for the resources created in this cft
  AmiId:
    Type: String
    Description: The AMI ID to use for the EC2 instance.
Resources:
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${TagOrg}-${TagTeam}-${TagApp}-${TagEnv}-EC2-SecurityGroup'
      GroupDescription: The EC2 Security Group. Open Traffic
      VpcId: !Ref MainVpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Organization
          Value: !Ref TagOrg
        - Key: Team
          Value: !Ref TagTeam
        - Key: Application
          Value: !Ref TagApp
        - Key: Purpose
          Value: 'EC2 security group for solitude project'
        - Key: Environment
          Value: !Ref TagEnv
  Ec2IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${TagOrg}-${TagTeam}-${TagApp}-${TagEnv}-IAM-InstanceProfile'
      Roles:
        - !Sub '${TagOrg}-${TagTeam}-${TagApp}-${TagEnv}-IAM-Role'
  MainEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      BlockDeviceMappings:
      - DeviceName: "/dev/xvda"
        Ebs:
          VolumeType: "gp2"
          VolumeSize: "16"
      ImageId: !Ref AmiId
      SecurityGroupIds:
        - !GetAtt Ec2SecurityGroup.GroupId
      SubnetId: !Ref MainVpcSubnetId
      KeyName: !Sub '${TagOrg}-${TagTeam}-${TagApp}-Shared-${MainSshKeyPairName}'
      IamInstanceProfile: !Ref Ec2IamInstanceProfile
      Tags:
        - Key: Organization
          Value: !Ref TagOrg
        - Key: Team
          Value: !Ref TagTeam
        - Key: Application
          Value: !Ref TagApp
        - Key: Purpose
          Value: 'Primary EC2 instance for solitude project'
        - Key: Environment
          Value: !Ref TagEnv
        - Key: Name
          Value: !Sub '${TagOrg}-${TagTeam}-${TagApp}-${TagEnv}-EC2-Instance'

