AWSTemplateFormatVersion: "2010-09-09"
Description: Fill Me In
Parameters:
  Env:
    Description: The Environment to append
    Type: String
  EBSKeyARN:
    Type: String
  SecurityGroupID: 
    Type: String
  IAMInstanceProfileName:
    Description: The Environment to append
    Type: String
  AMIId:
    Type: String
  SubnetID:
    Type: String
  SSHKey:
    Type: String
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Description: The EC2 Instance for project 2
    Properties:
      ImageId: !Ref AMIId
      KeyName: !Ref SSHKey
      Tags:
      - Key: Name
        Value: !Sub 'Corp5-Mythos-Valhalla-EC2-Instance-${Env}'
      BlockDeviceMappings:
      - DeviceName: "/dev/xvda"
        Ebs:
          VolumeType: "gp2"
          DeleteOnTermination: "false"
          VolumeSize: "16"
          Encrypted: true
          KmsKeyId: !Ref EBSKeyARN
      SecurityGroupIds:
        - !Ref SecurityGroupID
      IamInstanceProfile: !Sub '${IAMInstanceProfileName}-${Env}'
      InstanceType: t2.micro
      SubnetId: !Ref SubnetID
