AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role for EBS Volume Encryption
Parameters:
  RoleName:
    Type: String
Resources:
  IAMRole:
    Type: 'AWS::IAM::Role'
    Description: IAM Role for EBS Volume Encryption
    Properties:
      RoleName: !Ref RoleName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  IAMServiceLink:
      Type: 'AWS::IAM::ServiceLinkedRole'
      Properties:
        AWSServiceName: autoscaling.amazonaws.com
Outputs:
  IAMRoleArn:
    Value: !GetAtt IAMRole.Arn
  IAMRoleId:
    Value: !GetAtt IAMRole.RoleId
  IAMServiceLinkName:
    Value: !GetAtt IAMServiceLink.RoleName
