AWSTemplateFormatVersion: "2010-09-09"
Description: Project 1
Parameters:
  KMSKeyAlias:
    Type: String
  AccountID:
    Type: String
Resources:
  KmsKey:
    Type: "AWS::KMS::Key"
    Properties:
      EnableKeyRotation: True
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Administration of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::555887476308:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow the service role for auto scaling for this key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AccountID}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AccountID}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
            Action:
              - 'kms:CreateGrant'
            Resource: '*'
            Condition:
              Bool:
                "kms:GrantIsForAWSResource": true
  KMSAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub 'alias/${KMSKeyAlias}'
      TargetKeyId: !Ref KmsKey
Outputs:
  EBSKeyArn:
    Value: !GetAtt KmsKey.Arn