AWSTemplateFormatVersion: "2010-09-09"
Description: Project 1
Parameters:
  Env:
    Description: The Environment to append
    Type: String
  KMSKeyAlias:
    Description: The name for the KMS Key to be identified by
    Type: String
  IAMRoleARN:
    Description: The ARN of the IAM Role. This is from an Output.
    Type: String
  IAMInstanceProfileARN:
    Description: The ARN of the IAM Instance Profile. This is from an Output.
    Type: String
Resources:
  KmsKey:
    Type: "AWS::KMS::Key"
    Properties:
      EnableKeyRotation: True
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Key Administration
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::555887476308:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: The Key Usage for the EBS Encryption THE PROBLEM CHILD
            Effect: Allow
            Principal:
              AWS:
                - !Ref IAMRoleARN
                - 'arn:aws:iam::555887476308:role/aws:ec2-infrastructure/*'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
  KMSAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub 'alias/${KMSKeyAlias}-${Env}'
      TargetKeyId: !Ref KmsKey
Outputs:
  EBSKeyArn:
    Value: !GetAtt KmsKey.Arn
